version: '3.8'

services:
  gh-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JSDELIVR=false
      - CNPMJS=false
      # Uncomment to enable whitelist (comma-separated user/repo format)
      # - WHITELIST=golang/go,microsoft/vscode,facebook/react
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: add resource limits
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 256M
    #     reservations:
    #       cpus: '0.1'
    #       memory: 128M 